local Promise
Promise = require('Promise').Promise
local copas = require('copas');
((((((Promise(function(ok, ko)
  copas.sleep(1)
  return ok(1)
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return a + 1
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return a + 1
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return error(a + 1)
end)):finally(function(a, b)
  print("a: " .. tostring(a) .. ", b: " .. tostring(b))
  return copas.sleep(1)
end)):andthen((function(a)
  return print("Oops")
end), function(a)
  print(a)
  copas.sleep(1)
  return error(a + 1)
end)):catch(function(a)
  return print(a)
end)
return copas.loop()
