local Promise = require('.')
local eloop = require('eloop')
local copas = require('copas')
eloop.install();
((((((Promise(function(ok, ko)
  copas.sleep(1)
  return ok(1)
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return a + 1
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return a + 1
end)):andthen(function(a)
  print(a)
  copas.sleep(1)
  return error(a + 1)
end)):finally(function(a, b)
  print("a: " .. tostring(a) .. ", b: " .. tostring(b))
  return copas.sleep(1)
end)):andthen((function(a)
  print("Oops")
  return eloop.stop()
end), function(a)
  print(a)
  copas.sleep(1)
  return error(a + 1)
end)):catch(function(a)
  print(a)
  return eloop.stop()
end)
return copas.loop()
